name: Java CI

on:
  push:
    branches:
      - feature
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature/')
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: mvn -B test
        working-directory: Tictactoe

  build-and-upload-jar:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build JAR
        run: mvn -B package
        working-directory: Tictactoe
      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tictactoe-jar
          path: Tictactoe/target/*.jar 
